import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = 'http://localhost:5001/api';

function App(){
  const [mode,setMode]=useState('public');
  const [medicine,setMedicine]=useState('');
  const [results,setResults]=useState([]);
  const [network,setNetwork]=useState([]);
  const [facilities,setFacilities]=useState([]);
  const [loading,setLoading]=useState(false);
  const [message,setMessage]=useState('');const [deliveryForm,setDeliveryForm]=useState({inventoryId:'',customerName:'',customerPhone:'',deliveryAddress:'',quantity:1});
  const [deliveryOpen,setDeliveryOpen]=useState(false);
  function openDelivery(r){setDeliveryForm({inventoryId:r.inventory_id,customerName:'',customerPhone:'',deliveryAddress:'',quantity:1});setDeliveryOpen(true)}
  async function submitDelivery(e){e.preventDefault();try{const d=await api('/delivery/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(deliveryForm)});setMessage(`Delivery request #${d.id} created successfully`);setDeliveryOpen(false);doSearch();}catch(e){setMessage(e.message)}}

  const [adminTab,setAdminTab]=useState('facility');
  const [facilityForm,setFacilityForm]=useState({name:'',type:'Hospital',lat:'17.4065',lng:'78.4772',phone:'',address:'',license:''});
  const [inventoryForm,setInventoryForm]=useState({facilityId:'',medicineName:'',strength:'',quantity:'',expiry:''});

  async function api(path,options){ const r=await fetch(`${API}${path}`,options); const data=await r.json(); if(!r.ok) throw new Error(data.error||'Request failed'); return data; }
  async function search(){ if(!medicine.trim()) return; setLoading(true); setMessage(''); try{setResults(await api(`/search?medicine=${encodeURIComponent(medicine)}`));}catch(e){setMessage(e.message)}finally{setLoading(false)} }
  async function requestDelivery(row){try{const d=await api('/delivery/request',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sourceId:row.sourceId,medicine:row.medicine,quantity:1})});setMessage(`Request #${d.id} created. ${d.source} will be contacted.`);search();}catch(e){setMessage(e.message)}}
  async function loadNetwork(){try{setNetwork(await api('/network'));}catch(e){setMessage(e.message)}}
  async function loadFacilities(){try{setFacilities(await api('/facilities'));}catch(e){setMessage(e.message)}}
  useEffect(()=>{loadFacilities()},[]);
  async function addFacility(e){e.preventDefault();try{const d=await api('/admin/facilities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(facilityForm)});setMessage(`Facility added: ${d.name}`);setFacilityForm({name:'',type:'Hospital',lat:'17.4065',lng:'78.4772',phone:'',license:''});loadFacilities();}catch(e){setMessage(e.message)}}
  async function addInventory(e){e.preventDefault();try{await api('/admin/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(inventoryForm)});setMessage('Inventory saved to PostgreSQL.');setInventoryForm({...inventoryForm,medicineName:'',strength:'',quantity:'',expiry:''});loadNetwork();}catch(e){setMessage(e.message)}}
  const stockClass=s=>s==='LOW STOCK'?'low':s==='AVAILABLE'?'good':'limited';
  return <div className="app"><div className="gov-strip"><div className="gov-strip-inner"><span>Government digital service • Emergency medicine availability</span><span>Prototype • Smart India Hackathon 2026</span></div></div><header className="header"><div className="header-inner"><div className="brand"><div className="emblem">GOV</div><div><div className="brand-title">Emergency Medicine Availability</div><div className="brand-sub">Registered pharmacies, dispensaries & hospitals</div></div></div></div></header>
    <header><div><div className="brand">SIH1627</div><h1>Emergency Drug Locator</h1><p>Government medicine availability & surplus network</p></div><div className="tabs"><button className={mode==='public'?'active':''} onClick={()=>setMode('public')}>Public Search</button><button className={mode==='hospital'?'active':''} onClick={()=>{setMode('hospital');loadNetwork()}}>Hospital Portal</button><button className={mode==='admin'?'active':''} onClick={()=>{setMode('admin');loadFacilities()}}>Admin</button></div></header>
    {mode==='public'&&<main><section className="hero"><span className="badge">EMERGENCY ACCESS</span><h2>Find an essential medicine nearby</h2><p>One search checks registered pharmacies, dispensaries and hospitals in the PostgreSQL-backed network.</p><div className="search"><input value={medicine} onChange={e=>setMedicine(e.target.value)} onKeyDown={e=>e.key==='Enter'&&search()} placeholder="Search e.g. Insulin, Paracetamol, Amoxicillin"/><button onClick={search}>{loading?'Searching…':'Search'}</button></div><div className="examples">Try: <button onClick={()=>setMedicine('Insulin')}>Insulin</button><button onClick={()=>setMedicine('Paracetamol')}>Paracetamol</button><button onClick={()=>setMedicine('Amoxicillin')}>Amoxicillin</button></div></section>{message&&<div className="notice">{message}</div>}<section className="results"><div className="sectionTitle"><h3>Available sources</h3><span>{results.length} matches</span></div>{results.map((r,i)=><div className="card" key={i}><div><h3>{r.sourceName} <span className="verified">✓ Verified</span></h3><p>{r.type} · {r.distanceKm} km away · {r.phone}</p><p><strong>{r.medicine} {r.strength}</strong></p></div><div className="stock"><b>{r.quantity}</b><small>units</small><span className={stockClass(r.status)}>{r.status}</span></div><button className="action" onClick={()=>requestDelivery(r)}>Request</button></div>)}{!results.length&&<div className="empty">Search for a medicine to see live results from the PostgreSQL database.</div>}</section></main>}
    {mode==='hospital'&&<main><section className="hero hospital"><span className="badge">RESTRICTED HOSPITAL PORTAL</span><h2>Network inventory</h2><p>Identify shortages and surplus stock across connected facilities.</p><button onClick={loadNetwork}>Refresh inventory</button></section><section className="results"><div className="sectionTitle"><h3>Current stock</h3><span>{network.length} inventory records</span></div>{network.map((r,i)=><div className="card" key={i}><div><h3>{r.sourceName}</h3><p>{r.type} · {r.phone} · Expiry: {r.expiry?.slice(0,10)}</p><p><strong>{r.medicine} {r.strength}</strong></p></div><div className="stock"><b>{r.quantity}</b><small>units</small><span className={r.quantity<10?'low':r.quantity>30?'good':'limited'}>{r.quantity<10?'SHORTAGE':r.quantity>30?'SURPLUS':'NORMAL'}</span></div></div>)}</section></main>}
    {mode==='admin'&&<main><section className="hero admin"><span className="badge">ADMINISTRATION</span><h2>Manage the network database</h2><p>Add registered facilities and update their medicine inventory without editing code.</p><div className="adminTabs"><button className={adminTab==='facility'?'active':''} onClick={()=>setAdminTab('facility')}>Add Facility</button><button className={adminTab==='inventory'?'active':''} onClick={()=>setAdminTab('inventory')}>Add / Update Stock</button></div></section>{message&&<div className="notice">{message}</div>}<section className="adminPanel">{adminTab==='facility'?<form onSubmit={addFacility}><h3>Register hospital / dispensary / pharmacy</h3><div className="grid">{[['name','Facility name'],['phone','Phone number'],['license','Drug licence number'],['lat','Latitude'],['lng','Longitude']].map(([k,l])=><label key={k}>{l}<input required value={facilityForm[k]} onChange={e=>setFacilityForm({...facilityForm,[k]:e.target.value})}/></label>)}<label>Type<select value={facilityForm.type} onChange={e=>setFacilityForm({...facilityForm,type:e.target.value})}><option>Hospital</option><option>Dispensary</option><option>Pharmacy</option></select></label></div><button className="primary" type="submit">Add Facility to Database</button></form>:<form onSubmit={addInventory}><h3>Add / update medicine stock</h3><div className="grid"><label>Facility<select required value={inventoryForm.facilityId} onChange={e=>setInventoryForm({...inventoryForm,facilityId:e.target.value})}><option value="">Select facility</option>{facilities.map(f=><option key={f.id} value={f.id}>{f.name} · {f.type}</option>)}</select></label><label>Medicine name<input required value={inventoryForm.medicineName} onChange={e=>setInventoryForm({...inventoryForm,medicineName:e.target.value})}/></label><label>Strength<input required placeholder="e.g. 650 mg" value={inventoryForm.strength} onChange={e=>setInventoryForm({...inventoryForm,strength:e.target.value})}/></label><label>Quantity<input required type="number" min="0" value={inventoryForm.quantity} onChange={e=>setInventoryForm({...inventoryForm,quantity:e.target.value})}/></label><label>Expiry date<input required type="date" value={inventoryForm.expiry} onChange={e=>setInventoryForm({...inventoryForm,expiry:e.target.value})}/></label></div><button className="primary" type="submit">Save Stock to Database</button></form>}</section><section className="results"><div className="sectionTitle"><h3>Registered facilities</h3><span>{facilities.length}</span></div>{facilities.map(f=><div className="card" key={f.id}><div><h3>{f.name} <span className="verified">{f.verified?'✓ Verified':'Unverified'}</span></h3><p>{f.type} · {f.phone} · License: {f.license}</p></div></div>)}</section></main>}
    <footer>Prototype · PostgreSQL database · Mock licence verification · Emergency-use concept</footer>
  <footer className="footer"><div className="footer-inner"><strong>Emergency Medicine Availability Service</strong><br/>For urgent medicine searches. Availability is based on the latest reported inventory from registered facilities.</div></footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
